[package]
name = "rsql"
version = "0.1.0"
authors = ["Johannes Weissmann <jo@starsheriff.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
